# Generated by Django 3.2 on 2021-04-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travelapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=300)),
                ('traveler', models.CharField(max_length=150)),
                ('load_date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
